### ISSUE TITLE
Failed: Total 88, Failed 71, Errors 0, Passed 17 which is different from your tests.

### ISSUE THREAD

**Issue by nicolast0604** [diningyo/dirv#2]
info] ScalaTest
[info] Run completed in 25 minutes, 56 seconds.
[info] Total number of tests run: 88
[info] Suites: completed 14, aborted 0
[info] Tests: succeeded 17, failed 71, canceled 0, ignored 0, pending 0
[info] *** 71 TESTS FAILED ***
[error] Failed: Total 88, Failed 71, Errors 0, Passed 17
[error] Failed tests:
[error]         DirvRV32ITester
[error]         peri.uart.UartTopTester
[error]         mbus.MbusArbiterTester
[error]         peri.uart.RegTopTester
[error]         peri.mem.MemTopTester
[error]         SysUartTester
[error]         mbus.MbusDecoderTester
[error]         mbus.MbusSramBridgeTester
[error]         mbus.MbusICTester
[error]         DirvUartAccessTester
[error] (Test / test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 1570 s (26:10), completed Dec 2, 2019 5:49:33 AM

**Comment by diningyo** [comment]
Thanks for your reporting. And I'm sorry for my late replying.
As you mentioned this issue, sbt "test" command runs not only riscv-tests but whole test in this project.
When I updated for UART, I added test for UART and I didn't run riscv-tests. So I didn't realize fail of riscv-tests.
The commit  d63dfd6 through 1cdc28d, I fixed some issues in the CPU and riscv-tests results are OK now. Just now, I only maintained riscv-tests and another tests doesn't run I'll maintain remain tests...

**Comment by diningyo** [comment]
> Just now, I only maintained riscv-tests and another tests doesn't run I'll maintain remain tests...

I maintained another tests. Related commits are follow:

- 2c3ed7b850bdee9ef98497f1a51a784a03012800
- 2db6b0c0e1d3e2c3dae1f4c9527ac5eccf43520c
- 2e18ddf3f749582e7d67451aed0c2650e03504db
- 46dbc36d7f9ec19b9fca3de0c573111ea8220699

And I updated README/README_ja.md

- 4fee6f88cc86719f3bc11a031147242b8c3f32cf
